apiVersion: v1
kind: Secret
metadata:
    name: certdx-client-config
    namespace: certdx
    labels:
        app.kubernetes.io/name: certdx
        app.kubernetes.io/component: client
type: Opaque
stringData:
    client.toml: |
        [Http.MainServer]
        url = "https://certdxserver.example.com:10001/"
        token = "REPLACE_ME"

        [[Profile.Kubernetes]]
        name = "in-cluster"
        kubeConfig = ""

        [[Certificate]]
        name = "example"
        domains = [
            "*.example.com",
            "example.com",
        ]

        [[Certificate.UpdateAction]]
        type = "kubernetes"
        profile = "in-cluster"
