apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-domain
  namespace: istio-system
spec:
  secretName: tls-example.com
  dnsNames:
    - example.com

  renewBefore: 24h
  issuerRef:
    name: certdxclusterissuer-sample
    kind: CertDXClusterIssuer
    group: certdx.para.party