apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cert-manager-certdx-approval-role
rules:
  - apiGroups:
      - cert-manager.io
    resourceNames:
      - certdxclusterissuers.certdx.para.party/*
    resources:
      - signers
    verbs:
      - approve
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cert-manager-certdx-approval-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-certdx-approval-role
subjects:
  - kind: ServiceAccount
    name: cert-manager
    namespace: cert-manager
