apiVersion: v1
kind: Secret
metadata:
    name: certdx-kubernetes-updater-config
    namespace: certdx
    labels:
        app.kubernetes.io/name: certdx
        app.kubernetes.io/component: kubernetes-certificate-updater
type: Opaque
stringData:
    client.toml: |
        [Http.MainServer]
        url = "https://certdxserver.example.com:10001/"
        token = "REPLACE_ME"

        [[Certificate]]
        name = "example"
        domains = [
            "*.example.com",
            "example.com",
        ]
