apiVersion: v1
kind: ServiceAccount
metadata:
    name: certdx-kubernetes-updater
    namespace: certdx
    labels:
        app.kubernetes.io/name: certdx
        app.kubernetes.io/component: kubernetes-certificate-updater
